# Generated by Django 3.0.7 on 2020-06-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='superman',
            fields=[
                ('familyAccount', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=20, null=True)),
                ('number', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '家庭管理员',
                'verbose_name_plural': '家庭管理员',
                'db_table': 'superman',
            },
        ),
    ]
