# Generated by Django 3.0.7 on 2020-06-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200612_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='familyAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.superman'),
        ),
    ]
