# Generated by Django 3.0.7 on 2020-06-12 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200612_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.member'),
        ),
        migrations.AlterField(
            model_name='message',
            name='familyAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.superman'),
        ),
    ]
