# Generated by Django 3.0.7 on 2020-06-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200612_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='innerId',
        ),
        migrations.RemoveField(
            model_name='borrowandout',
            name='innerId',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='innerId',
        ),
        migrations.RemoveField(
            model_name='monthybill',
            name='innerId',
        ),
        migrations.AddField(
            model_name='bill',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='login.member'),
        ),
        migrations.AddField(
            model_name='borrowandout',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='login.member'),
        ),
        migrations.AddField(
            model_name='investment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='login.member'),
        ),
        migrations.AddField(
            model_name='monthybill',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='login.member'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='familyAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.superman'),
        ),
        migrations.AlterField(
            model_name='borrowandout',
            name='familyAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.superman'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='familyAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.superman'),
        ),
        migrations.AlterField(
            model_name='monthybill',
            name='familyAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.superman'),
        ),
        migrations.AlterField(
            model_name='note',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='login.member'),
        ),
    ]
