# Generated by Django 3.0.7 on 2020-06-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200612_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superman',
            name='number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
