# Generated by Django 3.0.7 on 2020-06-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200612_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowandout',
            name='addTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
