# Generated by Django 3.0.7 on 2020-06-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200618_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg',
            field=models.CharField(default='无', max_length=50),
        ),
    ]
