# Generated by Django 3.0.7 on 2020-06-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_message_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='addTime',
            field=models.DateTimeField(),
        ),
    ]
