# Generated by Django 3.0.7 on 2020-06-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200618_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowandout',
            name='addTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='investment',
            name='addTime',
            field=models.DateTimeField(),
        ),
    ]
