# Generated by Django 3.0.7 on 2020-06-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200618_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='myAccount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='addedTime',
            field=models.DateTimeField(),
        ),
    ]
